### PR TITLE
feat: Refactored the code to support testing async functions.

### PR DESCRIPTION
**Pull request by shichen85**
Hello,

Awesome work on this project!

We extended the project with the following changes:

1. All tests can support asynchronous functions with callbacks. This is done by binding a `done()` function to the object that processes asynchronous logics, so when the object finishes its operation, it can call `done()` to log the result, do harness `tear_down()`, and move on to the next test. This is demonstrated in the new `o_async` object in `BasicSample`. This allows testing functions such as `http_request()` and all functions that use the async events or logics that span over several steps.
1. `test_p` is reworked to only take 1 parameter instead of an array of parameters. This is mainly done to accommodate the async function testing, and the inner function can only take a single parameter anyway. However, the ability to test an array of parameters can still be achieved by running `test_p` inside an iteration loop of an array. This is demonstrated in the `ParameterizedTests`.
1. User can pass a callback function to be executed when the tests are completed, such as existing the runner. This is done through an additional param in `gmltest_start`.

Most of the changes are for the `*.gml` files, but `*.yy` files got changed as a side effect of IDE version and platform module access differences. I would highly recommend filtering the changes to only see `*.gml` changes in `src` to begin with.

Feel free to let me know if you have any questions regarding the changes, and thanks again for starting this project. We have been wanting a test framework like [Mocha](https://mochajs.org/) for GMS2, and your project helped us to jump-start the development.

### CODE REVIEW

**Comment by pmarincak** [comment]
Hi! 

Thanks a lot for taking the time to open the PR. I'm also happy to hear you've found it useful. Just wanted to let you know I'll try to give the PR a look over the next week or so. I'm sure the reason for aync is fairly obvious, but if you have any more context/information on the need for the feature that'd be great.

**Comment by shichen85** [comment]
Sure thing. Let's take implementing JavaScript's [setTimeout()](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) in GML as an example to demonstrate how we can test the implementation with gms2-test:

Because GML's async callback has to be mediated through objects, a `o_setTimeout_manager` object will look like: 
```js
///Create event 
callback = undefined;
alarm[0] = 1;

///alarm[0] event;
callback();
instance_destroy();
```

And the `setTimeout()` function will look like

```js
function setTimeout(callback_function, delay){
        var timeoutID = instance_create(o_setTimeout_manager);
        with timeoutID{
                callback = callback_function;
                alarm[0] = delay;
        }
        return timeoutID;
}
```

And when we use `setTimeout()`, it will look like

```js
score = 0;
setTimeout(function() => {
   score = 100;     
}, 10);

/// 10 steps later, the score variable should be set to 100
```

With gms2-test's current framework, we cannot easily verify that `score` is set to 100 in 10 steps:

```js
test("setTimeout test", function(){
        setTimeout(function() => {
                score = 100;     
        }, 10);
	gmltest_expect_eq(score, 100); // Test would fail because `setTimeout` and `gmltest_expect_eq` are executed in the same step, and score is not set until 10 steps later.
});
```

With this PR, the API will look like this:
```js
test("setTimeout test", function(_done){
        self.done = _done;
        var callback = method(self, function(){
                score = 100;
                gmltest_expect_eq(score, 100); // Test would succeed, because `gmltest_expect_eq` is executed at the time when `setTimeout` resolves, even though `setTimeout` is executed 10 steps earlier.
                done(); 
        })
        setTimeout(callback, 10);
}, true)
```

Essentially, with async functions like `setTimeout()`, we might be more interested in the resolution time state rather than the execution time state, thus it will be great if gms2-test can run the assertion tests at the resolution time.

**Comment by pmarincak** [comment]
Sorry for the delay! I was looking into a few things in order to respond.

I've taken the time to review the PR and in short, I agree with the feature request, but I don't think the implementation is where it needs to be to be merged. I'll go into more detail below, but if you want to close this and reopen later, or keep it open and update it, I'll leave it up to you.

-----

So the key reason why I'm against this implementation is because it will be introducing a breaking change by changing the API of all of the test functions, as well as requiring existing users to update all of their tests to call `done` at the end. I think that's way too much overhead for a user. I'm not sure how many people are using this framework, but I have over 800 tests with it, and it would require me to spend hours to upgrade existing tests. Not to mention, it isn't immediately obvious that you need to call `done`.

IIRC the `done` paradigm comes from mocha/jest though, so if you were referencing a specific framework or part of it, a link would be helpful. Either to the reference docs or maybe the related github code.

I've changed a framework like this in JS to support async, but javascript is able to have `await` and `async` keywords where we aren't able to here. However, those are just sugar syntax for promises, so I spent some time looking into it. I was certain someone had implemented it already, but it appears I misremembered and it was only talk. Of course, if I'm mistaken feel free to let me know. I gave it a shot to implement it, but it seems like it is a lot of work and complicated by the fact that GML lambda's don't capture local variables.

So with all that being said, I think the best thing to do is to create async versions of the existing `test_*` functions. For example: `test_p_async` or `async_test_p`.

- Keep all preexisting functions and signatures
- The async test_p function should be able to keep the array of parameters. The inner function should be called with the param at the time and the done callback
- We can keep the `isAsync` check in the struct, but similar to all the other functions, it is set when the test is created (ex. the disabled tests)
- We will have to change how the tests are executed. I suggest switching on the `isAsync` flag to have an `execute sync` and `execute async`. For a sync test the `done` callback is called for the user.
- Consider the case where a user forgets to call done, or some async operation fails but it doesn't fail the test. We should fail the test for taking too long.
- The user should be able to specify how long they want to wait via the test signature in milliseconds. The default should be 5000ms (this is the default for jest).

I think those are the key changes that need to be made. Feel free to make a commit per case, we can squash when it comes time to merge.

Once again, sorry for the delay, and thanks for opening this PR!

**Comment by shichen85** [comment]
Hello Paige,

Thanks for the reply and the thorough explanation.

I agree with your concerns that this PR's implementation is BREAKING and the functional gain does not justify the substantial migration cost for existing users.
I also agree with your implementation strategy to create async versions of the existing `test_*` functions, especially:

1. Timeout is necessary to prevent the tests from getting stuck either because of user implementation mistake or that the underlying GML functions hang
2. Sync functions can call `done()` for the user

As for the reference of `done()` paradigm in Mocha's async support, you can check out this [example](https://mochajs.org/#asynchronous-code). I am unaware of any existing open-source GML implementations either, so I would also be glad to see how others approached it.

Lastly, I will close this PR for now and update you when I have something else to show given the strategies we discussed. Thanks again for entertaining the PR!

**Comment by shichen85** [comment]
Hey Paige,

FYI, we have developed a test framework that supports async testing, and it is now public. Thought you might be interested in checking it out! https://github.com/bscotch/olympus

**Pull request closed without merging**
